---
- name: Install EPEL repository
  yum:
    name: epel-release
    state: present

- name: Installing nginx web server
  yum:
    name: nginx
    state: present
    update_cache: true
  notify: start nginx

- name: Linux | Create User
  user:
    name: www-data
    password: ''
    shell: /bin/bash

- name: Create a cache-dir
  file:
    path: "{{ fcgi_path }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
    recurse: yes

- name: Create a www-dir
  file:
    path: /var/www/wordpress
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
    recurse: yes

- name: Copying nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Adding permissive access
  command: semanage permissive -a httpd_t

- name: Enable nginx to be started at boot
  service:
    name: nginx
    enabled: yes
  notify:
    - start nginx
